[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< HEAD
actix-web = "4"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
dotenvy = "0.15"
chrono = "0.4"
sea-orm = { version = "0.12", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde_json = "1.0.149"
rust_decimal = "1.40.0"
bcrypt = "0.18.0"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
actix-multipart = "0.7.2"
futures-util = "0.3.32"
uuid = { version = "1", features = ["v4"] }
actix-files = "0.6.10"
=======
>>>>>>> refs/remotes/origin/main
